name: DakotaAC
version: '${project.version}'
main: skypixel.dakotaAC
description: Advanced, high-performance anti-cheat for modern Paper servers.
api-version: '1.21'
authors:
  - MaxUltimat3
website: https://modrinth.com/plugin/dakotaac
load: STARTUP
depend:
  - ProtocolLib

commands:
  dakotaac:
    description: Main DakotaAC command.
    usage: /dakotaac
    aliases:
      - dac
      - anticheat

permissions:
  dakotaac.command:
    description: Allows access to DakotaAC commands.
    default: op