name: DakotaAC
version: '0.18'
main: skypixel.dakotaAC
description: Advanced, high-performance anti-cheat for modern Paper servers.
api-version: '1.21'
authors:
  - MaxUltimat3
website: https://modrinth.com/plugin/dakotaac
load: STARTUP
depend:
  - ProtocolLib

commands:
  dakotaac:
    description: Main DakotaAC command.
    usage: /dakotaac
    aliases:
      - dac
      - anticheat
  report:
    description: Report a suspicious player.
    usage: /report <player>

permissions:
  dakotaac.command:
    description: Allows access to DakotaAC commands.
    default: op
  dakotaac.admin:
    description: Allows receiving report notifications and viewing the report book.
    default: op